trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - src/EmployerPR

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - src/EmployerPR

variables:
- group: Release Management Resources
- group: RELEASE das-apim-endpoints

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/1.0.7
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.6
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- template: ../../pipeline-templates/stage/outerapi-pipeline.yml
  parameters:
    OuterApiName: EmployerPR
    AdditionalProjectPathToInclude: src/Shared/SFA.DAS.SharedOuterApi.Employer.GovUK.Auth/SFA.DAS.SharedOuterApi.Employer.GovUK.Auth.csproj
    AdditionalTestProjectPathToInclude: src/Shared/SFA.DAS.SharedOuterApi.Employer.GovUK.Auth.UnitTests/SFA.DAS.SharedOuterApi.Employer.GovUK.Auth.UnitTests.csproj