trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - src/LearnerData
    exclude:
    - azure
    - pipeline-templates
    - deployments

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - src/LearnerData
    - Directory.Packages.props
    exclude:
    - azure
    - pipeline-templates
    - deployments

variables:
- group: Release Management Resources
- group: RELEASE das-apim-endpoints

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.2.19
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.19
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- template: ../../pipeline-templates/stage/outerapi-pipeline.yml
  parameters:
    OuterApiName: LearnerData
    AzureArtifactsFeed: dct-pkg
    ConfigurationSecrets:
      NServiceBusLicense: $(NServiceBusLicense)
      UserBearerTokenSigningKey: $(UserBearerTokenSigningKey)
      ApimEndpointsRedisConnectionString: $(ApimEndpointsRedisConnectionString)
