trigger:
  batch: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - deployments
    - src/FindAnApprenticeship

pr:
  autoCancel: true
  branches:
    include:
      - "master"
  paths:
    include:
    - azure
    - pipeline-templates
    - deployments
    - src/FindAnApprenticeship
    - Directory.Packages.props

variables:
- group: Release Management Resources
- group: RELEASE das-apim-endpoints
- group: RELEASE das-apim-endpoints-FindAnApprenticeship
- name: ProductShortName
  value: faa

resources:
  repositories:
  - repository: self
  - repository: das-platform-building-blocks
    type: github
    name: SkillsFundingAgency/das-platform-building-blocks
    ref: refs/tags/2.2.13
    endpoint: SkillsFundingAgency
  - repository: das-platform-automation
    type: github
    name: SkillsFundingAgency/das-platform-automation
    ref: refs/tags/5.1.19
    endpoint: SkillsFundingAgency
  pipelines:
  - pipeline: das-employer-config
    project: Digital Apprenticeship Service
    source: das-employer-config
    branch: master

stages:
- template: ../../pipeline-templates/stage/outerapi-pipeline.yml
  parameters:
    OuterApiName: das-at-faav2ui-as
    ConfigurationSecrets:
      NServiceBusLicense: $(NServiceBusLicense)
      ApimEndpointsRedisConnectionString: $(ApimEndpointsRedisConnectionString)
    useProductAppInsights: 'True'
    CheckClientCert: $True
    RunTests: 'True'
